apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-user-management
  namespace: microservices-demo
  labels:
    app: service1-user-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1-user-management
  template:
    metadata:
      labels:
        app: service1-user-management
    spec:
      containers:
      - name: service1
        image: microservices-demo/service1:debug
        imagePullPolicy: Never  # Use local images only
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 5678
          name: debug
        env:
        - name: SERVICE2_URL
          value: "http://service2-data-processing:8001"
        - name: SERVICE2_TIMEOUT
          value: "30"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: service1-user-management
  namespace: microservices-demo
  labels:
    app: service1-user-management
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 5678
    targetPort: 5678
    protocol: TCP
    name: debug
  selector:
    app: service1-user-management
